repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: modal-ci
        name: run modal ci tests
        entry: uvx modal run ci.py
        language: system
        pass_filenames: false
